### ISSUE TITLE
Error destroying component

### ISSUE THREAD

**Issue by sevab** [brewingcode/ember-google-publisher-tags#26]
Since upgrading from `v0.6.2` to `v3.0.2` the following error is being thrown twice within a couple of seconds after navigating away from the route that had `google-publisher-tag` component, and then every time I switch back and forth between tabs in my browser:

```
"Assertion Failed: calling set on destroyed object: <frontend@component:google-publisher-tag::ember5791>.inForeground = [object Boolean]"

"Error
    at assert (http://localhost:4200/assets/vendor.js:16916:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:27852:34)
    at set (http://localhost:4200/assets/vendor.js:32512:22)
    at HTMLDocument.<anonymous> (http://localhost:4200/assets/vendor.js:102759:25)
    at HTMLDocument.wrapped (http://localhost:4200/assets/vendor.js:72965:29)"
```

**Comment by brewingcode** [comment]
Right you are, sorry about that! I'll get a fix for that today.

**Comment by brewingcode** [comment]
Thanks for the report @sevab, please give v3.0.3+ a try.

**Comment by sevab** [comment]
@brewingcode All works, thanks!
